name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
    steps:
      - name: 'Init repository'
        uses: actions/checkout@v3
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php }}
      - name: 'Install dependencies'
        run: composer install
      - name: 'Run tests'
        run: vendor/bin/phpunit tests
      - name: 'Run phpstan'
        run: vendor/bin/phpstan analyse src --level=max